"""Updated profile

Revision ID: 3514ab865879
Revises: 8105b668d478
Create Date: 2025-06-17 00:52:38.283158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3514ab865879'
down_revision: Union[str, None] = '8105b668d478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Change summary column from nullable to NOT NULL
    # First update any existing NULL values to empty string
    op.execute("UPDATE profile SET summary = '' WHERE summary IS NULL")
    
    # Then alter the column to be NOT NULL
    op.alter_column('profile', 'summary',
                    existing_type=sa.Text(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert summary column back to nullable
    op.alter_column('profile', 'summary',
                    existing_type=sa.Text(),
                    nullable=True)
    # ### end Alembic commands ###
