"""Add queue_task_id, approval_context, screenshot_url, error_message, and notes to Application model for queue-based architecture

Revision ID: 8105b668d478
Revises: 96170a291ce2
Create Date: 2025-06-11 16:13:03.075506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8105b668d478'
down_revision: Union[str, None] = '96170a291ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new fields to application table for queue-based architecture
    op.add_column('application', sa.Column('queue_task_id', sa.String(), nullable=True))
    op.add_column('application', sa.Column('approval_context', sa.JSON(), nullable=True))
    op.add_column('application', sa.Column('screenshot_url', sa.String(), nullable=True))
    op.add_column('application', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('application', sa.Column('notes', sa.Text(), nullable=True))
    
    # Create index on queue_task_id for performance
    op.create_index(op.f('ix_application_queue_task_id'), 'application', ['queue_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove index and columns in reverse order
    op.drop_index(op.f('ix_application_queue_task_id'), table_name='application')
    op.drop_column('application', 'notes')
    op.drop_column('application', 'error_message')
    op.drop_column('application', 'screenshot_url')
    op.drop_column('application', 'approval_context')
    op.drop_column('application', 'queue_task_id')
    # ### end Alembic commands ###
