"""Add location, requirements, and salary to Role

Revision ID: 96170a291ce2
Revises: 925341dafe91
Create Date: 2025-06-09 19:55:18.977729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '96170a291ce2'
down_revision: Union[str, None] = '925341dafe91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('role', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('role', sa.Column('salary_range', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'salary_range')
    op.drop_column('role', 'requirements')
    op.drop_column('role', 'location')
    # ### end Alembic commands ###
